version: '3.1'
services:
  producer:
    build: .
    depends_on:
      - db_producer
    ports:
      - "8069:8069"
    volumes:
      - odoo-producer-data:/var/lib/odoo
      - ./producer/config_odoo_producer:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./producer/log_producer:/var/log/odoo
    environment:
      - HOST=db_producer
      - USER=odoo
      - PASSWORD=myodoo
    networks:
      ERP-BI:
        ipv4_address: "172.26.0.10"
    #command: odoo -u pedidos -d producer
  consumer:
    build: .
    depends_on:
      - db_consumer
    ports:
      - "8070:8069"
    volumes:
      - odoo-consumer-data:/var/lib/odoo
      - ./consumer/config_odoo_consumer:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./consumer/log_consumer:/var/log/odoo
    environment:
      - HOST=db_consumer
      - USER=odoo
      - PASSWORD=myodoo
    networks:
      ERP-BI:
        ipv4_address: "172.26.0.20"
    #command: odoo -u pedidos -d consumer
  db_producer:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db_producer-data:/var/lib/postgresql/data/pgdata
    networks:
      ERP-BI:
        ipv4_address: "172.26.0.30"
  db_consumer:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db_consumer-data:/var/lib/postgresql/data/pgdata
    networks:
      ERP-BI:
        ipv4_address: "172.26.0.40"
networks:
  ERP-BI:
    external: false
    name: ERP-BI
    ipam: 
      config:
        - subnet: "172.26.0.0/16"
volumes:
  odoo-producer-data:
  odoo-consumer-data:
  odoo-db_producer-data:
  odoo-db_consumer-data:

            