apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - nodePort: 31234
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT_INTERNAL://0.0.0.0:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT_INTERNAL:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT_INTERNAL://192.168.0.33:31234
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT_INTERNAL
        image: confluentinc/cp-kafka:7.0.1
        name: broker
        ports:
        - containerPort: 9092
